// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATbulPlkN_Nu-pYq5oQJt6bP9rHnMsWQ',
    appId: '1:108024299882:web:cfcda306f1f3991a67a513',
    messagingSenderId: '108024299882',
    projectId: 'vetements-3a4cb',
    authDomain: 'vetements-3a4cb.firebaseapp.com',
    storageBucket: 'vetements-3a4cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSo6mgwE-4pNnaTTUTRbGuLpStGUmH5zs',
    appId: '1:108024299882:android:6a0001bc551f958167a513',
    messagingSenderId: '108024299882',
    projectId: 'vetements-3a4cb',
    storageBucket: 'vetements-3a4cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4fyXsiW_lNJrSnddb1M6rQvJLaZWJ9uc',
    appId: '1:108024299882:ios:64bc0d6d5aaeb08867a513',
    messagingSenderId: '108024299882',
    projectId: 'vetements-3a4cb',
    storageBucket: 'vetements-3a4cb.firebasestorage.app',
    iosBundleId: 'com.fnine.tp2Vetements',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4fyXsiW_lNJrSnddb1M6rQvJLaZWJ9uc',
    appId: '1:108024299882:ios:64bc0d6d5aaeb08867a513',
    messagingSenderId: '108024299882',
    projectId: 'vetements-3a4cb',
    storageBucket: 'vetements-3a4cb.firebasestorage.app',
    iosBundleId: 'com.fnine.tp2Vetements',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBATbulPlkN_Nu-pYq5oQJt6bP9rHnMsWQ',
    appId: '1:108024299882:web:83c2ca70657d72e767a513',
    messagingSenderId: '108024299882',
    projectId: 'vetements-3a4cb',
    authDomain: 'vetements-3a4cb.firebaseapp.com',
    storageBucket: 'vetements-3a4cb.firebasestorage.app',
  );
}
